# Generated by Django 4.1.7 on 2023-03-07 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('basic', models.FloatField()),
                ('travel_allowance', models.FloatField()),
                ('house_allowance', models.FloatField()),
                ('medical_allowance', models.FloatField()),
                ('net_payable', models.FloatField()),
                ('provision_period', models.IntegerField(help_text='Month')),
                ('increment_period', models.IntegerField(help_text='increment month count')),
                ('increment_rate', models.FloatField(help_text='In percentage')),
                ('leave_in_cash_medical', models.FloatField(default=0.0, help_text='Medical Leave in cash, your submitted value will count as % percentage. It will automatically calculate to the employee salary sheet on year closing', verbose_name='Leave in Cash (Medical)')),
                ('leave_in_cash_casual', models.FloatField(default=0.0, help_text='Casual leave in cash, your submitted value will count as % percentage. It will automatically calculate to the employee salary sheet on year closing', verbose_name='Leave in Cash (Casual)')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('casual_leave', models.IntegerField()),
                ('medical_leave', models.IntegerField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(help_text='Use (,) comma for separate phone numbers', max_length=60)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('national_id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_date', models.DateField(blank=True, null=True)),
                ('tax_info', models.CharField(blank=True, help_text='i.e: 59530389237, Circle–138, Zone-11, Dhaka', max_length=255, null=True)),
                ('manager', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('show_in_web', models.BooleanField(default=True)),
                ('lunch_allowance', models.BooleanField(default=True)),
                ('project_eligibility', models.BooleanField(default=True)),
                ('leave_in_cash_eligibility', models.BooleanField(default=True)),
                ('show_in_attendance_list', models.BooleanField(default=True)),
                ('pf_eligibility', models.BooleanField(default=True)),
                ('list_order', models.IntegerField(default=100)),
                ('birthday_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('birthday_image_shown', models.BooleanField(default=False)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.designation')),
                ('leave_management', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.leavemanagement')),
                ('pay_scale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.payscale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
