# Generated by Django 3.2.18 on 2023-03-10 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_salaryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_leave', models.FloatField()),
                ('note', models.TextField(null=True)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('non_paid', 'Non Paid Leave')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✔ Approved'), ('rejected', '⛔ Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(150)])),
                ('status_changed_at', models.DateField(null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leave_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('status_changed_by', models.ForeignKey(limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_approve_leave_applications', 'Can able to approve leave applications'),),
            },
        ),
        migrations.CreateModel(
            name='LeaveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(help_text='Image , PDF or Docx file ', upload_to='')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leaveattachment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leave')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
